spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword
    schema: schema.sql
    data: data.sql

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG