spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: beranked
    password: beranked

logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

taco:
  orders:
    pageSize: 10