spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helenscake?serverTimezone=UTC
    username: root
    password: DEMOTOoth2017@
    hikari:
      connection-test-query: 'SELECT 1'

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG